  version: '3.8'

services:
  backend:
    build: ./backend/server
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend/app
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: backend
      MYSQL_USER: root
      MYSQL_PASSWORD: manager
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
