version: '3.8'
  
services:
  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: manager
      MYSQL_DATABASE: backend
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    container_name: spring-container
    build:
      context: ./backend/server
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/backend?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: manager
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    container_name: react-container
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8080/
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:
    name: db_data

networks:
  app-network:
    driver: bridge
